# Identify  error  (Home  work)
try:
	print('try suite')
except:  # ERROR:  default  except  should  be  at  the  end
	print('1st  default  except')
except:
	print('2nd  default  except')


'''
How  many  default  except  suites  are  permitted  for  a  try  suite ?  --->  1  (or)  0  but  not  more  than  one
'''